
package com.ws.nav_server.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://demo.nav_server.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeatherInfoByCityName", targetNamespace = "http://demo.nav_server.ws.com/", className = "com.ws.nav_server.demo.GetWeatherInfoByCityName")
    @ResponseWrapper(localName = "getWeatherInfoByCityNameResponse", targetNamespace = "http://demo.nav_server.ws.com/", className = "com.ws.nav_server.demo.GetWeatherInfoByCityNameResponse")
    @Action(input = "http://demo.nav_server.ws.com/WeatherServiceImpl/getWeatherInfoByCityNameRequest", output = "http://demo.nav_server.ws.com/WeatherServiceImpl/getWeatherInfoByCityNameResponse")
    public String getWeatherInfoByCityName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
